// ─── SAMPLE DATA ─────────────────────────────────────────────────────────────

export const INITIAL_BOOKS = [
  {
    id: 'utwb',
    title: 'Under the Whispering Door',
    author: 'TJ Klune',
    isbn: '9781250217349',
    format: 'print',
    spoilerMode: 'relaxed',
    status: 'reading',
    currentChapter: 18,
    totalChapters: 29,
    lastUpdated: '2026-05-04',
    coverBg: 'linear-gradient(160deg,#3A6647 0%,#2D5038 60%,#1E3828 100%)',
    mood: 'sage',
    readingLog: ['2026-05-02', '2026-05-03', '2026-05-04'],
    series: null,
    chapters: [
      { num:1,  title:"In Which Wallace Price Dies",       completed:true,  summary:"Wallace Price, a coldly efficient lawyer, dies suddenly mid-deposition. He wakes to find himself in an afterlife he didn't expect, greeted by Hugo—a warm, gentle ferryman—and his cat-obsessed trainee Mei.",              reflection:"The irony of a man who spent his life arguing is immediately rendered speechless.", important:false },
      { num:2,  title:"The Tea Shop at the End of the World", completed:true, summary:"Hugo runs Charon's Crossing, a tea shop that helps the recently deceased transition. Wallace is stubborn and refuses to accept his death. The shop hums with quiet magic and warmth.",                                reflection:null, important:true  },
      { num:3,  title:"Ghosts and Grievances",             completed:true,  summary:"Wallace meets Nelson, his grandfather's ghost who chose to linger. The difference between ferrymen and ghosts is explained. Wallace begins to see the kindness in Hugo's work.",                                           reflection:null, important:false },
      { num:4,  title:"The Door",                          completed:true,  summary:"The Whispering Door itself is glimpsed—a luminous threshold beyond which the dead pass on. Wallace resists going through it, insisting there's been a mistake.",                                                         reflection:null, important:false },
      { num:5,  title:"Tea and Questions",                 completed:true,  summary:"Hugo and Wallace have their first real conversation over tea. Wallace is surprised by how much he doesn't know about himself.",                                                                                           reflection:"Wallace's rigidity begins to crack here. His question 'Was I a good person?' is devastating.", important:true  },
      { num:6,  title:"The Manager",                       completed:true,  summary:"Charon, the immortal Manager, arrives to check on Hugo's progress with Wallace. She is ancient, eccentric, and clearly fond of Hugo. The stakes of getting Wallace to cross are raised.",                               reflection:null, important:false },
      { num:7,  title:"What We Leave Behind",              completed:true,  summary:"Wallace observes Hugo helping another soul cross. Watching someone else's goodbye breaks something open in Wallace.",                                                                                                     reflection:null, important:false },
      { num:8,  title:"The Living Return",                 completed:true,  summary:"Wallace's former colleague and rival visits his grave. Wallace watches people's reactions to his death and is humbled.",                                                                                                  reflection:null, important:false },
      { num:9,  title:"Mei's Story",                       completed:true,  summary:"Mei reveals her own backstory—why she became a ferryman and what she's still working through. Her grief mirrors Wallace's stubbornness.",                                                                                 reflection:null, important:false },
      { num:10, title:"The Weight of a Life",              completed:true,  summary:"Wallace begins to help in the tea shop, tentatively. He makes tea for a soul in distress. His first act of genuine selflessness.",                                                                                       reflection:"He puts someone else first for possibly the first time.", important:true  },
      { num:11, title:"Roots and Regrets",                 completed:true,  summary:"Hugo shows Wallace his garden—each plant tied to a soul he's helped cross. A living memorial. Wallace is moved.",                                                                                                        reflection:null, important:false },
      { num:12, title:"Night Talk",                        completed:true,  summary:"Wallace and Hugo talk late into the night. Hugo admits his own loneliness. Their connection deepens.",                                                                                                                    reflection:null, important:true  },
      { num:13, title:"The Rules of Ferrying",             completed:true,  summary:"Hugo explains the rules: ferrymen must not form attachments to the dead. Wallace is uncomfortable with what this implies.",                                                                                               reflection:null, important:false },
      { num:14, title:"A Ghost's Advice",                  completed:true,  summary:"Nelson counsels Wallace on regret and how to let go. He is tender and wise in a way Wallace's living family never was.",                                                                                                 reflection:null, important:false },
      { num:15, title:"The Record",                        completed:true,  summary:"Wallace learns more about his life from an outside perspective. The picture that emerges is sobering—competent but isolated.",                                                                                            reflection:null, important:false },
      { num:16, title:"Undone",                            completed:true,  summary:"Hugo makes a small but significant breach of ferryman rules, showing Wallace tenderness that crosses a professional line.",                                                                                               reflection:"Hugo breaks a rule for Wallace. This feels enormous.", important:true  },
      { num:17, title:"Something Grows",                   completed:true,  summary:"A new plant appears in Hugo's garden unbidden. Charon notices. Mei teases. The feeling between Hugo and Wallace can no longer be ignored.",                                                                               reflection:null, important:false },
      { num:18, title:"The Weight of Staying",             completed:true,  summary:"Wallace actively chooses to stay rather than cross over. He doesn't know how much longer he can hold on. Hugo quietly accepts his choice.",                                                                               reflection:null, important:true  },
      { num:19, title:"Consequences",         completed:false, summary:null, reflection:null, important:false },
      { num:20, title:"What Hugo Carries",    completed:false, summary:null, reflection:null, important:false },
      { num:21, title:"Mei Crosses a Line",   completed:false, summary:null, reflection:null, important:false },
      { num:22, title:"The Manager Returns",  completed:false, summary:null, reflection:null, important:false },
      { num:23, title:"Wallace's Decision",   completed:false, summary:null, reflection:null, important:false },
      { num:24, title:"Love in the Margins",  completed:false, summary:null, reflection:null, important:false },
      { num:25, title:"The Breach",           completed:false, summary:null, reflection:null, important:false },
      { num:26, title:"What We Fight For",    completed:false, summary:null, reflection:null, important:false },
      { num:27, title:"Hugo's Choice",        completed:false, summary:null, reflection:null, important:false },
      { num:28, title:"The Other Side of the Door", completed:false, summary:null, reflection:null, important:false },
      { num:29, title:"Epilogue: Still",      completed:false, summary:null, reflection:null, important:false },
    ],
    characters: {
      main: [
        { id:'w1', name:'Wallace Price',    role:'Protagonist',          status:'Deceased',         allegiance:'Himself → Hugo',       lastSeen:'Ch. 18', description:"A recently-dead lawyer. Efficient, cold, and deeply lonely. Learns tenderness through death.",             spoilerSafe:true, alive:false },
        { id:'w2', name:'Hugo',             role:'Ferryman',             status:'Living (immortal)', allegiance:'The Dead / Charon',    lastSeen:'Ch. 18', description:"Owner of Charon's Crossing tea shop. Warm, patient, gentle. Has guided countless souls across.",         spoilerSafe:true, alive:true  },
        { id:'w3', name:'Mei',              role:'Ferryman-in-training', status:'Living',            allegiance:'Hugo / The Work',      lastSeen:'Ch. 17', description:"Hugo's apprentice. Sharp, funny, hiding deep grief. Becomes Wallace's reluctant friend.",               spoilerSafe:true, alive:true  },
        { id:'w4', name:'Nelson',           role:'Lingering Ghost',      status:'Deceased (lingering)', allegiance:'Wallace / Memory', lastSeen:'Ch. 14', description:"Wallace's grandfather. Chose to stay as a ghost. Gentle, wise, full of old regrets.",                    spoilerSafe:true, alive:false },
      ],
      secondary: [
        { id:'w5', name:'Charon (the Manager)', role:'The Manager',     status:'Ancient / Immortal', allegiance:'The Balance',         lastSeen:'Ch. 13', description:"Ancient being who oversees all ferrymen. Eccentric, unpredictable, deeply fond of Hugo.",               spoilerSafe:true, alive:true  },
        { id:'w6', name:'Apollo',           role:"Hugo's Dog",           status:'Alive',              allegiance:'Hugo',                lastSeen:'Ch. 12', description:"A very good dog. Attached to Wallace almost immediately.",                                               spoilerSafe:true, alive:true  },
      ],
      relationships: [
        { from:'w1', to:'w2', label:'cautious love',      type:'love'      },
        { from:'w1', to:'w3', label:'reluctant warmth',   type:'ally'      },
        { from:'w1', to:'w4', label:'inherited grief',    type:'ally'      },
        { from:'w2', to:'w5', label:'answerable to',      type:'hierarchy' },
        { from:'w3', to:'w2', label:'apprentice',         type:'hierarchy' },
        { from:'w1', to:'w5', label:'under scrutiny',     type:'tension'   },
      ],
    },
    mysteries: [
      { id:'m1', text:"Why does Wallace's plant grow unbidden in Hugo's garden?", status:'hinted',   chapter:17, resolved:false },
      { id:'m2', text:"What exactly happens to ferrymen if they break the no-attachment rule?",        status:'open',    chapter:13, resolved:false },
      { id:'m3', text:"What is Charon's true nature — is she human or something else entirely?",       status:'open',    chapter:6,  resolved:false },
      { id:'m4', text:"Why did Nelson choose to stay behind instead of crossing?",                     status:'hinted',  chapter:3,  resolved:false },
      { id:'m5', text:"Is there any way for Wallace to remain permanently without crossing?",          status:'open',    chapter:18, resolved:false },
    ],
    notes: [
      { id:'n1', text:"The tea shop as liminal space — neither alive nor dead, neither coming nor going. The architecture of grief.",                   tag:'theme',     date:'2026-05-01' },
      { id:'n2', text:"\"Was I a good person?\" — Wallace's first honest question. All the armor drops at once.",                                       tag:'favorite',  date:'2026-05-02' },
      { id:'n3', text:"Theory: Hugo has been waiting for someone like Wallace specifically. The plant growing before he crosses feels intentional.",     tag:'theory',    date:'2026-05-04' },
      { id:'n4', text:"Confused by the Manager's rules — are ferrymen prohibited from love entirely, or only with souls they're guiding?",              tag:'confusing', date:'2026-05-03' },
    ],
    discussionQuestions: [
      "How does Wallace's profession as a lawyer — someone who argues for a living — contrast with what the afterlife asks of him?",
      "What does Charon's Crossing represent as a physical space? Why a tea shop specifically?",
      "TJ Klune uses humor throughout even in scenes of deep grief. How does that tonal balance affect the reading experience?",
      "Is Hugo's love for Wallace a breach of duty or a fulfillment of it?",
    ],
  },

  {
    id: 'mn',
    title: 'Mother Night',
    author: 'Kurt Vonnegut',
    isbn: null,
    format: 'ebook',
    spoilerMode: 'relaxed',
    status: 'reading',
    currentChapter: 22,
    totalChapters: 52,
    lastUpdated: '2026-04-28',
    coverBg: 'linear-gradient(160deg,#2C2C2C 0%,#1A1A1A 60%,#0F0F0F 100%)',
    mood: 'ember',
    readingLog: ['2026-04-22', '2026-04-25', '2026-04-28'],
    series: null,
    chapters: [
      { num:1, title:"Editor's Note",          completed:true, summary:"Vonnegut as editor introduces Howard W. Campbell Jr.'s memoir, setting up the moral frame: we are what we pretend to be.",                                                              reflection:"The warning is right there in the preface. Vonnegut doesn't hide it.", important:true  },
      { num:2, title:"The Last Artistic Creation", completed:true, summary:"Howard writes from an Israeli prison, awaiting trial for war crimes. He was a playwright and Nazi propagandist — but claims to have been an American spy.",                          reflection:null, important:false },
      { num:3, title:"Matriculation",           completed:true, summary:"Howard's early life in Germany, becoming a writer, falling in love with Helga.",                                                                                                        reflection:null, important:false },
      { num:4, title:"A Nation of Two",         completed:true, summary:"Howard and Helga create a private world — their love as its own country, insulated from ideology.",                                                                                     reflection:'"A nation of two." The loneliness of that eventually.', important:true  },
      { num:5, title:"The Recruitment",         completed:true, summary:"Frank Wirtanen, an American agent, recruits Howard to become a spy using his Nazi propaganda role as cover.",                                                                           reflection:null, important:false },
      { num:6, title:"The Playwright as Propagandist", completed:true, summary:"Howard creates genuinely vile propaganda, justifying it internally as service to the Allied cause.",                                                                            reflection:null, important:false },
      ...Array.from({ length: 16 }, (_, i) => ({
        num: i + 7, title: `Chapter ${i + 7}`, completed: true,
        summary: 'Howard navigates his double life in postwar New York, a man without a country or a cause.',
        reflection: null, important: false,
      })),
      ...Array.from({ length: 30 }, (_, i) => ({
        num: i + 23, title: `Chapter ${i + 23}`, completed: false,
        summary: null, reflection: null, important: false,
      })),
    ],
    characters: {
      main: [
        { id:'mn1', name:'Howard W. Campbell Jr.', role:'Narrator / Protagonist', status:'Imprisoned',      allegiance:'Unknown — the question of the novel', lastSeen:'Ch. 22', description:"American-born playwright turned Nazi propagandist — or spy. He himself isn't sure which matters more.", spoilerSafe:true, alive:true  },
        { id:'mn2', name:'Helga Noth',             role:'Wife',                   status:'Presumed Dead',   allegiance:'Howard / Art',                         lastSeen:'Ch. 4',  description:"Howard's great love. German actress. Her memory is his only anchor.",                                   spoilerSafe:true, alive:false },
      ],
      secondary: [
        { id:'mn3', name:'Frank Wirtanen', role:'American Agent', status:'Unknown', allegiance:'US Government', lastSeen:'Ch. 5', description:"The man who recruited Howard. May be the only person who knows the truth about Howard's work.", spoilerSafe:true, alive:true },
      ],
      relationships: [
        { from:'mn1', to:'mn2', label:'anchor / absence', type:'love'    },
        { from:'mn1', to:'mn3', label:'recruiter',        type:'tension' },
      ],
    },
    mysteries: [
      { id:'mn_m1', text:"Is Howard actually a spy or has he convinced himself of a comforting lie?", status:'open',   chapter:2, resolved:false },
      { id:'mn_m2', text:"What happened to Helga — is she truly dead?",                               status:'hinted', chapter:4, resolved:false },
      { id:'mn_m3', text:"Will Frank Wirtanen come forward to exonerate Howard?",                      status:'open',   chapter:5, resolved:false },
    ],
    notes: [
      { id:'mn_n1', text:'"We are what we pretend to be." The whole novel is contained in that sentence.',                                              tag:'theme',  date:'2026-04-25' },
      { id:'mn_n2', text:"Howard's propaganda is genuinely harmful regardless of intent. Can good intentions retroactively clean bad acts?",           tag:'theory', date:'2026-04-27' },
    ],
    discussionQuestions: [
      "Vonnegut's moral: \"we are what we pretend to be.\" Does the novel bear that out or complicate it?",
      "Is Howard Campbell a war criminal, a patriot, or simply a man who loved too personally in a political world?",
      "How does the framing device (Vonnegut as editor) change how we read Howard's confessions?",
    ],
  },

  {
    id: 'rot',
    title: 'The Republic of Thieves',
    author: 'Scott Lynch',
    isbn: null,
    format: 'print',
    spoilerMode: 'full',
    status: 'finished',
    currentChapter: 25,
    totalChapters: 25,
    lastUpdated: '2026-03-15',
    coverBg: 'linear-gradient(160deg,#7B1C1C 0%,#5A1010 60%,#3D0A0A 100%)',
    mood: 'ember',
    readingLog: ['2026-03-10', '2026-03-12', '2026-03-14', '2026-03-15'],
    series: { name: 'Gentleman Bastard Sequence', position: 3, total: 7 },
    chapters: Array.from({ length: 25 }, (_, i) => ({
      num: i + 1, title: `Chapter ${i + 1}`, completed: true,
      summary: 'A completed entry in the ongoing saga of Locke Lamora and Jean Tannen.',
      reflection: null, important: i === 12 || i === 20 || i === 24,
    })),
    characters: {
      main: [
        { id:'rot1', name:'Locke Lamora',      role:'Protagonist / Con Artist', status:'Alive (barely)', allegiance:'Jean / The Crooked Warden',  lastSeen:'Ch. 25', description:"The Thorn of Camorr. A legendary thief with a self-destructive streak and a face full of aliases.", spoilerSafe:true, alive:true  },
        { id:'rot2', name:'Jean Tannen',        role:'Partner / Best Friend',    status:'Alive',          allegiance:'Locke',                       lastSeen:'Ch. 25', description:"The muscle, the heart, the brain. The most competent person in any room.",                           spoilerSafe:true, alive:true  },
        { id:'rot3', name:'Sabetha Belacoros',  role:'Love Interest / Rival',    status:'Alive',          allegiance:'Herself / The Bondsmagi',     lastSeen:'Ch. 25', description:"Locke's great love and greatest adversary. Red-haired, brilliant, justifiably furious.",          spoilerSafe:true, alive:true  },
      ],
      secondary: [
        { id:'rot4', name:'Patience', role:'Bondsmage', status:'Alive', allegiance:'The Bondsmagi', lastSeen:'Ch. 24', description:"Assigns Locke and Jean to a complex job involving Sabetha.", spoilerSafe:true, alive:true },
      ],
      relationships: [
        { from:'rot1', to:'rot2', label:'brothers in arms',  type:'ally'      },
        { from:'rot1', to:'rot3', label:'beloved adversary', type:'love'      },
        { from:'rot3', to:'rot1', label:'unresolved love',   type:'tension'   },
        { from:'rot4', to:'rot1', label:'puppet master',     type:'hierarchy' },
      ],
    },
    mysteries: [
      { id:'rot_m1', text:"Who was Locke in his past life — the Bondsmagi's hints suggest something extraordinary.", status:'hinted',  chapter:20, resolved:false },
      { id:'rot_m2', text:"What are Sabetha's real loyalties at the end?",                                           status:'hinted',  chapter:25, resolved:false },
    ],
    notes: [
      { id:'rot_n1', text:"The Espara flashbacks are some of the most delightful writing in the whole series. Teenage Locke is both funnier and more vulnerable.",          tag:'favorite', date:'2026-03-10' },
      { id:'rot_n2', text:"The revelation about Locke's past identity hit differently than I expected. Lynch is patient with his reveals.",                                  tag:'theme',    date:'2026-03-14' },
    ],
    discussionQuestions: [
      "How does Sabetha's presence change the dynamic between Locke and Jean established in the first two books?",
      "The Espara flashbacks are a play-within-a-novel — what does Lynch accomplish by using this structure?",
      "What do you make of the Bondsmagi's revelation about Locke's origins? Do you believe them?",
    ],
  },

  {
    id: 'maniac',
    title: 'The MANIAC',
    author: 'Benjamín Labatut',
    isbn: null,
    format: 'audiobook',
    spoilerMode: 'strict',
    status: 'reading',
    currentChapter: 8,
    totalChapters: 26,
    lastUpdated: '2026-05-05',
    coverBg: 'linear-gradient(160deg,#1A2A4A 0%,#0F1F3A 60%,#080F1E 100%)',
    mood: 'ink',
    readingLog: ['2026-05-04', '2026-05-05'],
    series: null,
    chapters: [
      { num:1, title:"Prologue: Paul Ehrenfest",  completed:true, summary:"A shattering prologue about physicist Paul Ehrenfest's mental collapse and final act. Labatut establishes his territory: the dark underbelly of brilliant minds.",          reflection:"Opens with a murder-suicide. The book announces its theme immediately: what does pure intellect cost?", important:true  },
      { num:2, title:"The Child Prodigy",         completed:true, summary:"Young John von Neumann's uncanny mathematical gifts. Those who witnessed him describe something almost inhuman.",                                                             reflection:null, important:false },
      { num:3, title:"Budapest, 1903",            completed:true, summary:"Von Neumann's upbringing among Budapest's Jewish intellectual elite. The world that produced him.",                                                                         reflection:null, important:false },
      { num:4, title:"God's Messenger",           completed:true, summary:"Multiple voices describe von Neumann's mind — the testimonies build a portrait of a man who seemed to exist outside normal limits.",                                        reflection:null, important:false },
      { num:5, title:"The Architect of Destruction", completed:true, summary:"Von Neumann's role in the Manhattan Project. His mathematical contributions to the bomb's design.",                                                                    reflection:"He calculated blast radii for maximum civilian casualties. Labatut holds this without flinching.", important:true  },
      { num:6, title:"MANIAC",                    completed:true, summary:"The Mathematical Analyzer, Numerator, Integrator, and Computer. Von Neumann's machine that would reshape the world.",                                                      reflection:null, important:false },
      { num:7, title:"The Game",                  completed:true, summary:"Von Neumann's game theory work and its application to nuclear deterrence. Mutual assured destruction as a mathematical proof.",                                             reflection:null, important:false },
      { num:8, title:"The Mind and the Machine",  completed:true, summary:"Von Neumann begins to question the boundary between human thought and computation. His final illness looms.",                                                               reflection:null, important:false },
      ...Array.from({ length: 18 }, (_, i) => ({
        num: i + 9, title: `Part II — ${i + 9}`, completed: false,
        summary: null, reflection: null, important: false,
      })),
    ],
    characters: {
      main: [
        { id:'man1', name:'John von Neumann',   role:'Subject',          status:'Historical Figure', allegiance:'Mathematics / America / The Future', lastSeen:'Ch. 8', description:"One of the 20th century's greatest minds. Architect of game theory, digital computing, and the hydrogen bomb.", spoilerSafe:true, alive:false },
      ],
      secondary: [
        { id:'man2', name:'Paul Ehrenfest',      role:'Prologue Figure',  status:'Deceased',          allegiance:'Physics / Despair',    lastSeen:'Ch. 1', description:"Physicist who could not reconcile quantum mechanics with his own sense of reality.",                      spoilerSafe:true, alive:false },
        { id:'man3', name:'Various Witnesses',   role:'Chorus',           status:'Historical',        allegiance:'Memory',               lastSeen:'Ch. 8', description:"Scientists, colleagues, family — their testimonies build the portrait of von Neumann.",                    spoilerSafe:true, alive:true  },
      ],
      relationships: [
        { from:'man1', to:'man2', label:'dark precursor',  type:'tension'   },
        { from:'man3', to:'man1', label:'bear witness to', type:'hierarchy' },
      ],
    },
    mysteries: [
      { id:'man_m1', text:"Was von Neumann genuinely disturbed by what he helped create, or did he remain detached to the end?", status:'open', chapter:5, resolved:false },
      { id:'man_m2', text:"What is Labatut's own moral position — does the book condemn von Neumann or celebrate him?",          status:'open', chapter:1, resolved:false },
      { id:'man_m3', text:"How does the Lee Sedol / AlphaGo section (Part III) connect to von Neumann's story?",                 status:'open', chapter:8, resolved:false },
    ],
    notes: [
      { id:'man_n1', text:"Labatut walks the line between non-fiction and invented testimony. I can't always tell which voices are real. That feels intentional.", tag:'confusing', date:'2026-05-05' },
      { id:'man_n2', text:'"The MANIAC" — the machine and the man share a name. The question of who is computing whom.',                                           tag:'theme',     date:'2026-05-05' },
    ],
    discussionQuestions: [
      "Labatut blurs fact and fiction. How does this hybrid form affect your reading of von Neumann as a historical figure?",
      "The book opens with catastrophe and destruction. What does Labatut suggest about the relationship between genius and harm?",
      "How does the digital age we're living in color how you read about the machine's creation?",
    ],
  },

  {
    id: 'sv',
    title: 'Starter Villain',
    author: 'John Scalzi',
    isbn: '9780765389220',
    format: 'audiobook',
    spoilerMode: 'full',
    status: 'finished',
    currentChapter: 22,
    totalChapters: 22,
    lastUpdated: '2026-02-20',
    coverBg: 'linear-gradient(160deg,#8B4513 0%,#6B3010 60%,#4A1F08 100%)',
    mood: 'gold',
    readingLog: ['2026-02-17', '2026-02-18', '2026-02-19'],
    series: null,
    chapters: Array.from({ length: 22 }, (_, i) => ({
      num: i + 1, title: `Chapter ${i + 1}`, completed: true,
      summary: "Charlie navigates his surprising inheritance — turns out his uncle was a genuinely formidable supervillain.",
      reflection: null, important: i === 4 || i === 10 || i === 18 || i === 21,
    })),
    characters: {
      main: [
        { id:'sv1', name:'Charlie Fitzer', role:'Protagonist',        status:'Alive (unexpectedly)', allegiance:'Himself / Chaos',          lastSeen:'Ch. 22', description:"A substitute teacher/failed bar owner who inherits his uncle's villain empire. Endearingly overwhelmed.",   spoilerSafe:true, alive:true },
        { id:'sv2', name:'Mathilda',       role:'Cat Union Leader',   status:'Very Much Alive',      allegiance:'Cat Union / Charlie (reluctantly)', lastSeen:'Ch. 21', description:"Leader of the genetically-enhanced cat labor union. Negotiates aggressively. Takes no nonsense.", spoilerSafe:true, alive:true },
      ],
      secondary: [
        { id:'sv3', name:'Jake Baldwin', role:'Villain Ally',       status:'Alive',    allegiance:'Charlie',      lastSeen:'Ch. 20', description:"One of the villain operatives who ends up in Charlie's corner.",    spoilerSafe:true, alive:true  },
        { id:'sv4', name:'Uncle Jake',   role:'The Previous Villain', status:'Deceased', allegiance:'Evil (loosely)', lastSeen:'Ch. 1',  description:"The original villain. More competent than Charlie ever imagined.", spoilerSafe:true, alive:false },
      ],
      relationships: [
        { from:'sv1', to:'sv2', label:'uneasy alliance',  type:'tension' },
        { from:'sv1', to:'sv4', label:'inherits the mess', type:'hierarchy' },
        { from:'sv3', to:'sv1', label:'unexpectedly loyal', type:'ally'    },
      ],
    },
    mysteries: [
      { id:'sv_m1', text:"Is the cat union situation ever truly resolved?", status:'resolved', chapter:21, resolved:true },
    ],
    notes: [
      { id:'sv_n1', text:"The cat union is a stroke of genius. Scalzi commits fully to the bit and it pays off.",                       tag:'favorite', date:'2026-02-18' },
      { id:'sv_n2', text:"The villain-as-late-stage-capitalism metaphor works better than it has any right to.",                       tag:'theme',    date:'2026-02-20' },
    ],
    discussionQuestions: [
      "How does Scalzi use the supervillain genre to comment on inherited wealth and power structures?",
      "The cats are deeply funny but also the most organized characters in the book. What's the joke here?",
      "Would you call Charlie a villain by the end? What makes someone a villain vs. a person doing villainous things?",
    ],
  },
];

// ─── CONFIG MAPS ─────────────────────────────────────────────────────────────

export const STATUS_CONFIG = {
  reading:  { label:'Reading',      dot:'bg-sage',      text:'text-sage',      bg:'bg-sage-bg',    border:'border-sage-pale'    },
  finished: { label:'Finished',     dot:'bg-gold',      text:'text-gold',      bg:'bg-gold-bg',    border:'border-gold-border'  },
  paused:   { label:'Paused',       dot:'bg-ink-400',   text:'text-ink-500',   bg:'bg-ink-100',    border:'border-ink-200'      },
  want:     { label:'Want to Read', dot:'bg-sienna',    text:'text-sienna',    bg:'bg-sienna-bg',  border:'border-sienna-pale'  },
};

export const TAG_CONFIG = {
  theory:    { label:'Theory',    cls:'tag-theory'    },
  favorite:  { label:'Favourite', cls:'tag-favorite'  },
  confusing: { label:'Confusing', cls:'tag-confusing' },
  theme:     { label:'Theme',     cls:'tag-theme'     },
  character: { label:'Character', cls:'tag-character' },
  quote:     { label:'Quote',     cls:'tag-quote'     },
};
